apiVersion: v1 
kind: PersistentVolumeClaim
metadata: 
 name: dynamic-demo
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: roboshop-ebs
  resources:
   requests:
    storage: 4Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: dynamic-demo
spec:
  containers:
   - name: nginx
     image: nginx
     volumeMounts:
      - name: persistent-storage
        mountPath: /usr/share/nginx/html
  volumes: 
   - name: persistent-storage
     persistentVolumeClaim:
      claimName: dynamic-demo


