apiVersion: v1
kind: pod
metadata: 
  name: roboshop
  labels:
    purpose: demo
spec:
  containers:
    - name: nginx
      image: nginx
    - name: almalinux
      image: almalinux:9
      command: ["sleep","1000"]
    