apiVersion: v1 
kind: Pod
metadata: 
  name: pod-config
  labels: 
    purpose: demo
    env: dev
spec:
  containers: 
  - name: nginx
    image: nginx
    envFrom:
    - configMapRef:
        name: pod-config
