apiVersion: v1 
kind: Pod
metadata: 
 name: demo
 labels: 
  purpose: demo 
  env: dev
spec: 
  containers:
   - name: nginx
     image: nginx
     envFrom:
      - secretsRef:
           name: pod-secret
