apiVersion: v1
kind: Service
metadata: 
  name: service-demo-np
  labels:
    project: demo 
    env: dev
spec:
  type: NodePort
  selector:
     purpose: demo-np
     project: roboshop
  ports:
    - targetPort: 80
      port: 80
      protocol: TCP
---
apiVersion: v1
kind: Pod 
metadata: 
 name: service-demo-pod
 labels: 
   purpose: demo-np
   project: roboshop
spec:
 containers:
 - name: nginx
   image: nginx


