apiVersion: v1
kind: Service
metadata: 
  name: service-demo-lb
  labels:
    project: demo 
    env: dev
spec:
  type: LoadBalancer
  selector:
     purpose: demo-lb
     project: roboshop
  ports:
    - targetPort: 80
      port: 80
      protocol: TCP
---
apiVersion: v1
kind: Pod 
metadata: 
 name: service-demo-pod-lb
 labels: 
   purpose: demo-lb 
   project: roboshop
spec:
 containers:
 - name: nginx
   image: nginx


