apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset-demo
  labels:
    name: replica-demo 
    project: dev
  spec:
    replicas: 2
    selector:
     matchLabels: 
       purpose: demo
       project: roboshop
       env: dev
    template:
      metadata:
        name: replica-pod
        labels: 
          purpose: demo
          project: roboshop
          env: dev
    spec:
      containers:  
       - name: nginx
         image: nginx
